name: bitme
description: Offline chat over Bluetooth and WiFi.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  nearby_connections: ^4.3.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon.png
  adaptive_icon_background: "#3A5BFF"
  adaptive_icon_foreground: assets/icon_fg.png
